language: python
python:
  - "3.7"

install:
  - pip install numpy
  - pip install .
  - python -c "from pymoo.util.function_loader import is_compiled;print('Compiled Extensions: ', is_compiled())"


script:
  - python tests/test_suite.py
