name: testing
on:
  push:
    branches:
      - develop

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install -r tests/requirements.txt
      - name: Install pymoo
        run: |
          pip install .
          rm -rf pymoo
      - name: Run Tests
        run: pytest


  build:
     needs: testing
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
         python-version: ['3.7', '3.8', '3.9']
         exclude:
           - os: ubuntu-latest
             python-version: '3.7'
           - os: ubuntu-latest
             python-version: '3.8'
     steps:
     - uses: actions/checkout@v2
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install setuptools wheel numpy
     - uses: knicknic/os-specific-run@v1
       with:
         linux: python setup.py sdist
         macos: python setup.py bdist_wheel
         windows: python setup.py bdist_wheel
     - uses: actions/upload-artifact@v2
       with:
         name: dist
         path: dist

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@v2
       with:
         name: dist
         path: dist
     - name: Upload
       uses: trendyminds/github-actions-rsync@master
       with:
         RSYNC_OPTIONS: -avzr --delete --exclude '*.ipynb'
         RSYNC_TARGET: /home/releases/${BRANCH_NAME}
         RSYNC_SOURCE: /dist/*
       env:
         SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
         SSH_USERNAME: ${{secrets.SSH_USERNAME}}
         SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
