name: testing
on:
  push:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Install pymoo
        run: |
          pip install .
          rm -rf pymoo
      - name: List Directory
        run: |
          pwd
          ls -la .
          ls -la tests/resources/problems
          ls /home/runner/work/pymoo/pymoo/tests/resources/problems/WFG/
          ls /home/runner/work/pymoo/pymoo/tests/resources/problems/WFG/10obj
          cat /home/runner/work/pymoo/pymoo/tests/resources/problems/WFG/10obj/WFG9.x
      - name: Run Tests
        run: pytest
