name: testing
on:
  push:
    branches:
      - master
      - develop
      - release
  pull_request:
    branches:
      - master
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run tests with pytest
        run: pytest tests/test_performance_indicator.py 
